server:
  port: 8761
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 90000
  client:
    register-with-eureka: false
    fetch-registry: false
    #defaultZone: http://localhost:8762/eureka
spring:
  application:
    name: castle-eureka-server
  #profiles: slavea
  
#---
#server:
#  port: 8762
#eureka:
#  server:
#      enable-self-preservation: true
#      eviction-interval-timer-in-ms: 90000
#  client:
#    defaultZone: http://localhost:8761/eureka
#spring:
#  profiles: slaveb
#  application:
#      name: eureka-server
